### ISSUE TITLE
Instructions on how to use stream wall

### ISSUE THREAD

**Issue by amarmashruwala** [streamwall/streamwall#124]
Hi there, are there some instructions or a video on how to do streamwall? 

I tried adding a twitch stream but it didn't load up. Maybe I am doing something wrong. 
Thank you

**Comment by sayhiben** [comment]
hey there - sorry you're having trouble. I'm trying to update this app, and one of the things I'm looking at  is making it easier to run. In the meantime, if you follow the readme _exactly_, it should work the way it's described. If you're still interested in this project, consider watching it, and you'll be updated when it gets new commits
